version: '2'
services:
    landexp-app:
        image: landexp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://landexp-mysql:3306/landexp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    landexp-mysql:
        extends:
            file: mysql.yml
            service: landexp-mysql
